app/routes/auth.py
from flask import Blueprint,jsonify, render_template, request, redirect, url_for, flash, session
from werkzeug.security import generate_password_hash, check_password_hash
from ..models.userM import User
from ..models.itemM import Item
from ..models.factionM import Faction
from ..extensions import db
from functools import wraps
from ..forms.loginform import LoginForm
from flask_login import login_user, current_user, LoginManager
from ..models.disciplineM import Discipline
from ..models.groupM import Group  # Импортируйте модель Group

auth = Blueprint('auth', __name__)

# Инициализация Flask-Login
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.login_message = 'Пожалуйста, войдите в систему, чтобы получить доступ к этой странице.'

# Загрузка пользователя по user_id
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

from ..models.groupM import Group  # Импортируйте модель Group

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        last_name = request.form.get('last_name')
        first_name = request.form.get('first_name')
        patronymic = request.form.get('patronymic')
        email = request.form.get('email')
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')
        group_ids = request.form.getlist('groups ')
        teacher_ids = request.form.getlist('teachers')

        # Проверка на существующего пользователя
        existing_user = User.query.filter((User.email == email) | (User.username == username)).first()
        if existing_user:
            flash('Пользователь с таким email или никнеймом уже существует.', 'danger')
            return redirect(url_for('auth.register'))

        if password != confirm_password:
            flash('Пароли не совпадают. Попробуйте еще раз.', 'danger')
            return redirect(url_for('auth.register'))

        # Создание нового пользователя
        new_user = User(
            username=username,
            last_name=last_name,
            first_name=first_name,
            patronymic=patronymic,
            email=email,
            status='новичок',
            level=1,
            cube_coins=0,
            experience=0,
            position='ученик',
            is_teacher=False,
            is_admin=False
        )
        new_user.set_password(password)

        # Добавление групп и учителей
        for group_id in group_ids:
            group = Group.query.get(group_id)
            if group:
                new_user.add_to_group(group)
        
        for teacher_id in teacher_ids:
            teacher = User.query.get(teacher_id)
            if teacher and teacher.is_teacher:
                new_user.add_teacher(teacher)

        db.session.add(new_user)
        db.session.commit()

        flash('Регистрация прошла успешно! Вы можете войти в систему.', 'success')
        return redirect(url_for('auth.login'))
    else:
        groups = Group.query.all()
        teachers = User.query.filter_by(is_teacher=True).all()
        return render_template('auth/register.html', teachers=teachers, groups=groups)

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'user_id' not in session:
            flash('Пожалуйста, войдите в систему, чтобы получить доступ к этой странице.', 'warning')
            return redirect(url_for('auth.login'))
        return f(*args, **kwargs)

    return decorated_function

@auth.route('/profile')
@login_required
def own_profile():
    return redirect(url_for('auth.view_profile', user_id=current_user.id))

@auth.route('/logout')
@login_required
def logout():
    if 'user_id' in session:
        session.clear()
        flash('Вы вышли из системы', 'success')
        return redirect(url_for('auth.login'))
    else:
        flash('Вы не авторизованы', 'danger')
        return redirect(url_for('auth.login'))

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if not user:
            flash('Пользователь не найден', 'danger')
            return redirect(url_for('auth.login'))

        if user and user.check_password(password):
            login_user(user)
            session['user_id'] = user.id
            print("User ID stored in session:", session.get('user_id'))
            print("Current user:", current_user)
            flash('Вы успешно вошли в систему!', 'success')
            return redirect(url_for('post.index'))
        else:
            flash('Неправильный email или пароль.', 'error')

    return render_template('auth/login.html', form=form)

@auth.route('/register_teacher', methods=['GET', 'POST'])
def register_teacher():
    if request.method == 'POST':
        username = request.form.get('username')
        last_name = request.form.get('last_name')
        first_name = request.form.get('first_name')
        patronymic = request.form.get('patronymic')
        email = request.form.get('email')
        password = request.form.get('password')

        # Проверка на существование пользователя с таким же email или username
        existing_user = User.query.filter((User.email == email) | (User.username == username)).first()
        if existing_user:
            flash('Пользователь с таким email или username уже существует.', 'danger')
            return redirect(url_for('auth.register_teacher'))

        # Проверка на правильность пароля
        if not password:
            flash('Пароль не может быть пустым.', 'danger')
            return redirect(url_for('auth.register_teacher'))

        # Создание нового пользователя
        new_user = User(
            username=username,
            last_name=last_name,
            first_name=first_name,
            patronymic=patronymic,
            email=email,
            password=generate_password_hash(password),
            is_teacher=True
        )

        # Добавление нового пользователя в базу данных
        db.session.add(new_user)

        db.session.commit()
        flash('Регистрация прошла успешно!', 'success')
        return redirect(url_for('auth.login'))
    
    return render_template('auth/register_teacher.html')

@auth.route('/profile/<int:user_id>')
@login_required
def view_profile(user_id):
    user = User.query.get_or_404(user_id)
    if user.is_admin:
        return render_template('auth/admin_profile.html', user=user)
    elif user.is_teacher:
        return render_template('auth/teacher_profile.html', user=user)
    else:
        # Получаем все предметы пользователя
        user_items = user.items
        return render_template('auth/student_profile.html', user=user, items=user_items)

@auth.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    groups = Group.query.all()
    teachers = User.query.filter_by(is_teacher=True).all()
    factions = Faction.query.all()  # Добавляем запрос для получения всех фракций
    if request.method == 'POST':
        if current_user.is_admin:
            current_user.username = request.form.get('username', current_user.username)
            current_user.contact_info = request.form.get('contact_info', current_user.contact_info)
        elif current_user.is_teacher:
            current_user.username = request.form.get('username', current_user.username)
            current_user.last_name = request.form.get('last_name', current_user.last_name)
            current_user.first_name = request.form.get('first_name', current_user.first_name)
            current_user.patronymic = request.form.get('patronymic', current_user.patronymic)
            current_user.birthday = request.form.get('birthday', current_user.birthday)
            current_user.avatar = request.form.get('avatar', current_user.avatar)
            current_user.bio = request.form.get('bio', current_user.bio)
            current_user.pedstage = request.form.get('pedstage', current_user.pedstage)
            current_user.contact_info = request.form.get('contact_info', current_user.contact_info)
            current_user.telegram_link = request.form.get('telegram_link', current_user.telegram_link)
            current_user.discord_link = request.form.get('discord_link', current_user.discord_link)
        else:
            current_user.username = request.form.get('username', current_user.username)
            current_user.last_name = request.form.get('last_name', current_user.last_name)
            current_user.first_name = request.form.get('first_name', current_user.first_name)
            current_user.patronymic = request.form.get('patronymic', current_user.patronymic)
            current_user.birthday = request.form.get('birthday', current_user.birthday)
            current_user.avatar = request.form.get('avatar', current_user.avatar)
            current_user.bio = request.form.get('bio', current_user.bio)
            current_user.contact_info = request.form.get('contact_info', current_user.contact_info)
            current_user.telegram_link = request.form.get('telegram_link', current_user.telegram_link)
            current_user.discord_link = request.form.get('discord_link', current_user.discord_link)
            current_user.status = request.form.get('status', current_user.status)
            current_user.level = request.form.get('level', current_user.level)
            current_user.cube_coins = request.form.get('cube_coins', current_user.cube_coins)
            current_user.experience = request.form.get('experience', current_user.experience)

app/routes/student.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from ..models.userM import User
from ..models.groupM import Group
from ..extensions import db
from flask_login import current_user, login_required
from ..models.disciplineM import Discipline
from ..decorators import teacher_required
from ..models.itemM import Item
from ..models.achievementM import Achievement

student = Blueprint('student', __name__)

@student.route('/disciplines')
@login_required
def disciplines():
    disciplines = Discipline.query.all()
    return render_template('teacher/disciplines.html', disciplines=disciplines)


@student.route('/student_info/<int:student_id>')
def student_info(student_id):
    student = User.query.get(student_id)
    if student:
        return render_template('teacher/student_info.html', student=student)
    else:
        return 'Ученик не найден'

@student.route('/pashalka')
def pashalka():
    return render_template('student/pashalka.html')

from flask import Blueprint, render_template, request
from flask_login import login_required
from ..models.userM import User
from ..models.disciplineM import Discipline
from ..models.groupM import Group

@student.route('/students/<int:discipline_id>')
@login_required
def students_by_discipline(discipline_id):
    groups = Group.query.all()
    teachers = User.query.filter_by(is_teacher=True).all()
    filters = {}
    if request.args.get('group'):
        filters['group_id'] = request.args.getlist('group')
    if request.args.get('teacher'):
        filters['teacher_id'] = request.args.getlist('teacher')
    if request.args.get('min_level'):
        filters['level__gte'] = int(request.args.get('min_level'))
    if request.args.get('max_level'):
        filters['level__lte'] = int(request.args.get('max_level'))
    if request.args.get('position'):
        filters['position'] = request.args.getlist('position')

    if discipline_id == 0:  # 0 будет означать "Все дисциплины"
        students = User.query.filter_by(is_teacher=False)
        discipline = {"name": "Все дисциплины"}
    else:
        discipline = Discipline.query.get_or_404(discipline_id)
        students = User.query.filter_by(is_teacher=False, discipline_id=discipline_id)

    if 'group_id' in filters:
        students = students.filter(User.groups.any(Group.id.in_(filters['group_id'])))
    if 'teacher_id' in filters:
        students = students.filter(User.teacher_id.in_(filters['teacher_id']))
    if 'level__gte' in filters:
        students = students.filter(User.level >= filters['level__gte'])
    if 'level__lte' in filters:
        students = students.filter(User.level <= filters['level__lte'])
    if 'position' in filters:
        students = students.filter(User.position.in_(filters['position']))

    sort = request.args.get('sort', 'last_name')
    if sort == 'last_name':
        students = students.order_by(User.last_name)
    elif sort == 'first_name':
        students = students.order_by(User.first_name)
    elif sort == 'level':
        students = students.order_by(User.level)

    students = students.all()

    return render_template('teacher/students.html', discipline=discipline, groups=groups, teachers=teachers, students=students)

@student.route('/reward_students', methods=['POST'])
@login_required
@teacher_required
def reward_students():
    data = request.json
    if not data or 'students' not in data:
        return jsonify({'status': 'error', 'message': 'Некорректные данные запроса'}), 400

    try:
        students = User.query.filter(User.id.in_(data['students'])).all()
        if not students:
            return jsonify({'status': 'error', 'message': 'Студенты не найдены'}), 404

        for student in students:
            if 'experience' in data:
                experience = int(data['experience'])
                student.add_experience(experience)
            if 'gold' in data:
                student.cube_coins += int(data['gold'])
            if 'item' in data and data['item']:
                item = Item.query.get(data['item'])
                if item:
                    student.items.append(item)
            if 'achievement' in data and data['achievement']:
                achievement = Achievement.query.get(data['achievement'])
                if achievement:
                    student.achievements.append(achievement)

        db.session.commit()

        return jsonify({
            'status': 'success',
            'message': 'Ученики успешно награждены',
            'rewarded_students': len(students)
        })

    except Exception as e:
        db.session.rollback()
        return jsonify({
            'status': 'error',
            'message': f'Произошла ошибка при награждении учеников: {str(e)}'
        }), 500

app/templates/main/_footer.html
<footer class="footer mt-auto py-2">
  <div class="container-fluid">
      <div class="row align-items-center">
          <div class="col-auto">
              <img src="{{ url_for('static', filename='img/catinhat.png') }}" alt="Cat in Hat" class="footer-image" id="catInHat">
              <span id="clickCounter" style="display: none;">0</span>
          </div>
          <div class="col">
              <hr class="footer-line">
          </div>
      </div>
  </div>
</footer>

<script>
let clickCount = 0;
const catImage = document.getElementById('catInHat');
const clickCounter = document.getElementById('clickCounter');

catImage.addEventListener('click', function() {
  clickCount++;
  clickCounter.textContent = clickCount;
  clickCounter.style.display = 'inline';
  
  if (clickCount === 300) {
      window.open("{{ url_for('student.pashalka') }}", '_blank');
  }
});
</script>

app/templates/main/_header.html
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
  <div class="col-md-3 mb-2 mb-md-0">
      <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
          <img class="header__img" src="{{url_for('static', filename='img/ITCubeLogo.png')}}" alt="student">
      </a>
  </div>

  <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
      {% if current_user.is_authenticated %}
          {% if current_user.is_teacher %}
              <li><a href="/" class="nav-link px-2">Мероприятия</a></li>
              <li><a href="/quests" class="nav-link px-2">Квесты</a></li>
              <li><a href="{{ url_for('student.disciplines') }}" class="nav-link px-2">Ученики</a></li>
              <li><a href="/shop" class="nav-link px-2">Магазин</a></li>
              <li><a href="/lore" class="nav-link px-2">Лор</a></li>
              <li><a href="/factions" class="nav-link px-2">Факультет</a></li>
          {% elif current_user.is_admin %}
              <li><a href="/quests" class="nav-link px-2">Квесты</a></li>
              <li><a href="{{ url_for('admin.teachers_list') }}" class="nav-link px-2">Преподаватели</a></li>
              <li><a href="{{ url_for('student.disciplines') }}" class="nav-link px-2">Ученики</a></li>
              <li><a href="/shop" class="nav-link px-2">Магазин</a></li>
              <li><a href="/lore" class="nav-link px-2">Лор</a></li>
              <li><a href="/factions" class="nav-link px-2">Факультет</a></li>
              <li><a href="#" class="nav-link px-2">Критические настройки</a></li>
          {% else %}
              <li><a href="/" class="nav-link px-2">События</a></li>
              <li><a href="/quests" class="nav-link px-2">Квесты</a></li>
              <li><a href="/factions" class="nav-link px-2">Факультет</a></li>
              <li><a href="/shop" class="nav-link px-2">Магазин</a></li>
              <li><a href="/lore" class="nav-link px-2">Лор</a></li>
          {% endif %}
      {% else %}
          <li><a href="/how" class="nav-link px-2">Как стать it-шником</a></li>
          <li><a href="/team" class="nav-link px-2">Команда</a></li>
          <li><a href="/about" class="nav-link px-2">О нас</a></li>
      {% endif %}
  </ul>

  <div class="col-md-3 text-end">
    {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.own_profile') }}" class="btn btn-secondary me-2">{{ current_user.username }}</a>
        <a href="{{ url_for('auth.logout') }}" class="btn btn-primary">Выйти</a>
    {% else %}
        <a href="{{ url_for('auth.login') }}" class="btn btn-primary">Войти</a>
        <a href="{{ url_for('auth.register') }}" class="btn btn-primary">Зарегистрироваться</a>
        <a href="{{ url_for('auth.register_teacher') }}" class="btn btn-primary">Зарегистрировать педагога</a>
    {% endif %}
  </div>
</header>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{url_for('static', filename='css/libs/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="{{url_for('static',filename='js/libs/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/app.js')}}"></script>
    <script src="{{ url_for('static', filename='js/notifications.js') }}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    {% block scripts %}{% endblock %}
    <header class="header">{% include 'main/_header.html' %}</header>
    <div id="notification-modal" class="modal">
        <div id="itemNotification" class="item-notification" style="display: none;">
            <h3>Вы получили предмет!</h3>
            <p>Название: <span id="itemName"></span></p>
            <p>Описание: <span id="itemDescription"></span></p>
            <button id="acceptButton">Принять</button>
            <button id="inventoryButton">Зайти в инвентарь</button>
        </div>
    </div>
    <main class="content">
        {% block content %}{% endblock %}
    </main>
    <footer class="footer">{% include 'main/_footer.html' %}</footer>

    <script>
        $(document).ready(function() {
            toastr.options = {
                "closeButton": true,
                "debug": false,
                "newestOnTop": false,
                "progressBar": true,
                "positionClass": "toast-top-right",
                "preventDuplicates": false,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut"
            }

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        var type = "{{ category }}";
                        switch(type){
                            case 'info':
                                toastr.info("{{ message }}");
                                break;
                            case 'success':
                                toastr.success("{{ message }}");
                                break;
                            case 'warning':
                                toastr.warning("{{ message }}");
                                break;
                            case 'error':
                                toastr.error ("{{ message }}");
                                break;
                            default:
                                toastr.info("{{ message }}");
                        }
                    {% endfor %}
                {% endif %}
            {% endwith %}
        });
    </script>
</body>
</html>